/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BlocklistVaultDiffAbi,
  BlocklistVaultDiffAbiInterface,
} from "../BlocklistVaultDiffAbi";

const _abi = [
  {
    inputs: [],
    name: "blocklistManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_blocklistManager",
        type: "address",
      },
    ],
    name: "setBlocklistManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "updateBlocklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BlocklistVaultDiffAbi__factory {
  static readonly abi = _abi;
  static createInterface(): BlocklistVaultDiffAbiInterface {
    return new Interface(_abi) as BlocklistVaultDiffAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BlocklistVaultDiffAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BlocklistVaultDiffAbi;
  }
}
