/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  GenesisVaultDiffAbi,
  GenesisVaultDiffAbiInterface,
} from "../GenesisVaultDiffAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "osTokenShares",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "referrer",
        type: "address",
      },
    ],
    name: "depositAndMintOsToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "osTokenShares",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "rewardsRoot",
            type: "bytes32",
          },
          {
            internalType: "int160",
            name: "reward",
            type: "int160",
          },
          {
            internalType: "uint160",
            name: "unlockedMevReward",
            type: "uint160",
          },
          {
            internalType: "bytes32[]",
            name: "proof",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IKeeperRewards.HarvestParams",
        name: "harvestParams",
        type: "tuple",
      },
    ],
    name: "updateStateAndDepositAndMintOsToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class GenesisVaultDiffAbi__factory {
  static readonly abi = _abi;
  static createInterface(): GenesisVaultDiffAbiInterface {
    return new Interface(_abi) as GenesisVaultDiffAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GenesisVaultDiffAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as GenesisVaultDiffAbi;
  }
}
