/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  GnosisVaultDiffAbi,
  GnosisVaultDiffAbiInterface,
} from "../GnosisVaultDiffAbi";

const _abi = [
  {
    inputs: [],
    name: "swapXdaiToGno",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class GnosisVaultDiffAbi__factory {
  static readonly abi = _abi;
  static createInterface(): GnosisVaultDiffAbiInterface {
    return new Interface(_abi) as GnosisVaultDiffAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GnosisVaultDiffAbi {
    return new Contract(address, _abi, runner) as unknown as GnosisVaultDiffAbi;
  }
}
