/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RestakingVaultDiffAbi,
  RestakingVaultDiffAbiInterface,
} from "../RestakingVaultDiffAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newRestakeOperatorsManager",
        type: "address",
      },
    ],
    name: "setRestakeOperatorsManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newRestakeWithdrawalsManager",
        type: "address",
      },
    ],
    name: "setRestakeWithdrawalsManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "restakeOperatorsManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "createEigenPod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RestakingVaultDiffAbi__factory {
  static readonly abi = _abi;
  static createInterface(): RestakingVaultDiffAbiInterface {
    return new Interface(_abi) as RestakingVaultDiffAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RestakingVaultDiffAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RestakingVaultDiffAbi;
  }
}
