import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'


const sidebars: SidebarsConfig = {
  setup: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

}


export default sidebars
