/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BlocklistVaultDiffAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blocklistManager"
      | "setBlocklistManager"
      | "updateBlocklist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "blocklistManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBlocklistManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBlocklist",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "blocklistManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlocklistManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBlocklist",
    data: BytesLike
  ): Result;
}

export interface BlocklistVaultDiffAbi extends BaseContract {
  connect(runner?: ContractRunner | null): BlocklistVaultDiffAbi;
  waitForDeployment(): Promise<this>;

  interface: BlocklistVaultDiffAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blocklistManager: TypedContractMethod<[], [string], "view">;

  setBlocklistManager: TypedContractMethod<
    [_blocklistManager: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBlocklist: TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blocklistManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBlocklistManager"
  ): TypedContractMethod<
    [_blocklistManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBlocklist"
  ): TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
