/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PrivateVaultDiffAbiInterface extends Interface {
  getFunction(
    nameOrSignature: "whitelister" | "setWhitelister" | "updateWhitelist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "whitelister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelister",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "whitelister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
}

export interface PrivateVaultDiffAbi extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateVaultDiffAbi;
  waitForDeployment(): Promise<this>;

  interface: PrivateVaultDiffAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  whitelister: TypedContractMethod<[], [string], "view">;

  setWhitelister: TypedContractMethod<
    [_whitelister: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWhitelist: TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "whitelister"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setWhitelister"
  ): TypedContractMethod<[_whitelister: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelist"
  ): TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
