/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RestakingVaultDiffAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "setRestakeOperatorsManager"
      | "setRestakeWithdrawalsManager"
      | "restakeOperatorsManager"
      | "createEigenPod"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setRestakeOperatorsManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRestakeWithdrawalsManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "restakeOperatorsManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEigenPod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "setRestakeOperatorsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRestakeWithdrawalsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restakeOperatorsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEigenPod",
    data: BytesLike
  ): Result;
}

export interface RestakingVaultDiffAbi extends BaseContract {
  connect(runner?: ContractRunner | null): RestakingVaultDiffAbi;
  waitForDeployment(): Promise<this>;

  interface: RestakingVaultDiffAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setRestakeOperatorsManager: TypedContractMethod<
    [newRestakeOperatorsManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setRestakeWithdrawalsManager: TypedContractMethod<
    [newRestakeWithdrawalsManager: AddressLike],
    [void],
    "nonpayable"
  >;

  restakeOperatorsManager: TypedContractMethod<[], [string], "view">;

  createEigenPod: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setRestakeOperatorsManager"
  ): TypedContractMethod<
    [newRestakeOperatorsManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRestakeWithdrawalsManager"
  ): TypedContractMethod<
    [newRestakeWithdrawalsManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "restakeOperatorsManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createEigenPod"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
