name: Check build and types

on:
  pull_request:
    branches: [ main, prod ]

jobs:
  build_check:
    name: Build check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
        with:
          version: 10.25.0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '24.12.0'

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run Build check
        run: pnpm prepare && pnpm rollup
