name: Check SDK types

on:
  pull_request:
    branches: [ main, prod ]

jobs:
  check_sdk_branch:
    name: Main branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Types check
        run: 'npx tsc'
